CREATE DATABASE IF NOT EXISTS linkedin_db;

USE linkedin_db;

CREATE TABLE IF NOT EXISTS users(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
content TEXT NOT NULL,
image BLOB,
created_at DATETIME
);

CREATE TABLE IF NOT EXISTS comments(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
comment_content VARCHAR(200),
post_id BIGINT,
FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS user_profiles(
id INT AUTO_INCREMENT PRIMARY KEY,
profile_picture BLOB,
profile_background_picture BLOB,
full_name VARCHAR(50) NOT NULL,
introduction TEXT,
bio TEXT,
education VARCHAR(200),
location VARCHAR(200),
certification VARCHAR(200),
user_id BIGINT,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);