#spring.application.name=fs-1st-backend
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/signup
#spring.datasource.username=root
#spring.datasource.password=12341234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring:
  application:
    name: fs-1st-backend

  doc:
    swagger-ui:
      enabled: true

  api-docs:
    path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  datasource:
    url: jdbc:mysql://localhost:3306/signup
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
