#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/signup
#    username: root
#    password: 12341234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#
